异常时程序经常会出现的，发现错误的最佳时机是在编译阶段，也就是你试图在运行程序之前。但是，在编译期间并不能找到所有的错误，有一些 `NullPointerException` 和 `ClassNotFoundException` 异常在编译期找不到，这些异常是 `RuntimeException` 运行时异常，这些异常往往在运行时才能被发现。

我们写 Java 程序经常会出现两种问题，一种是 java.lang.Exception，一种是 java.lang.Error，都用来表示出现了异常情况，下面就针对这两种概念进行理解。

#### 认识Exception

`Exception` 位于 `java.lang` 包下，它是一种顶级接口，继承于 `Throwable` 类，Exception 类及其子类都是 Throwable 的组成条件，是程序出现的合理情况。

在认识Exception 之前，有必要先了解一下什么是 `Throwable`

#### 什么是Throwable

Throwable 类是 Java 语言中所有 `错误(errors)` 和`异常(exceptions)`的父类。只有继承于 Throwable的类或者其子类才能够被抛出，还有一种方式是带有 Java 中的 `@throw` 注解的类也可以抛出。

在 Java 规范中，对非受查异常和受查异常的定义是这样的：

也就是说，除了 `RuntimeException` 和其子类，以及`error`和其子类，其它的所有异常都是`checkedException`。

那么，按照这种逻辑关系，我们可以对 Throwable 及其子类进行归类分析。

![](http://blog.tryna.top/img/2022-01-19-14-00-27.png)

可以看到，Throwable 位于异常和错误的最顶层，我们查看 Throwable类中发现它的方法和属性有很多，我们只讨论其中几个比较常用的。

```java
// 返回抛出异常的详细信息
public String getMessage();
public String getLocalizedMessage();

// 返回异常发生时的简要描述
public String toString();

// 打印异常信息到标准输出流上
public void printStackTrace();
public void printStackTrace(PrintStream s);
public void printStackTrace(PrintWriter s);

// 记录栈帧的当前状态
public synchronized Throwable fillInStackTrace();
```

此外，因为 Throwable 的父类也是 `Object`, 所以常用的方法还有继承其父类的`getClass()` 和 `getName()` 方法。

#### 常见的Exception

Exception有两种异常，一种是 `RuntimeException`, 是运行期的异常，编译的时候可以通过，但运行的时候会抛出来；一种是`IOException` , 是编译期的异常，一般是强制处理的，否则就会编译失败，这两种异常都应该去捕获。

下面列出了一些常见的异常：

**RuntimeException：**

| 异常名称 | 异常描述 |
|--|--|
| ArrayIndexOutofBoundsException | 数组越界异常 |
| NullPointerException | 空指针异常 |
| IllegalArgumentException | 非法参数异常 |
| NegativeArraySizeException | 数组长度为负异常 |
| IllegalStateException | 非法状态异常 |
| ClassCastException | 类型转换异常 |

**IOException**

| 异常名称 | 异常描述 |
|--|--|
| NoSuchFieldException | 表示该类没有指定名称抛出来的异常 |
| NoSuchMethodException | 表示该类没有指定方法抛出来的异常 |
| IllegalAccessException | 不允许访问某个类的异常 |
| ClassNotFoundException | 类没有找到抛出异常 |


#### 与 Exception 有关的关键字

在 Java 中有这几个关键字 **throws、throw、try、finally、catch** 与异常有关。
